name: "forum"
mode: "dev"
port: 8080
version: "v0.0.1"

# 雪花算法：开始时间 机器ID
start_time: "2024-03-14"
machine_id: 1

log:
  level: "debug"
  filename: "forum.log"
  max_size: 200
  max_age: 30
  max_backups: 7
database:
  dbtype: "mysql"
  host: "192.168.255.3"
  port: 3306
  user: "root"
  password: "root"
  dbname: "forum"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100